---
name: Github CI

on:
  pull_request:
    branches:
      - master
      - beta
  push:
    branches:
      - master
      - beta

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint commit messages
        run: npx commitlint --from origin/master --to HEAD

      - name: ESLint
        run: npm run lint

      - name: Test and report
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
          npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Semantic release
        run: npx semantic-release
        if: success()
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
